### ISSUE TITLE
MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by jebscc** [XYOracleNetwork/api-archivist-nodejs#264]
Was able to get this built into Docker but I am getting an error when running the archivist container.

Thought it might be my antivirus or firewall so I disabled both but still getting this error.

![image](https://user-images.githubusercontent.com/19239389/230672222-785cd3b4-d3db-4317-bfa7-b5fb56470a29.png)

**Here is what I have in the docker-compose.yml file**

version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: archivist
    healthcheck:
      test:
        [
          "CMD",
          "/usr/bin/mongosh",
          "-u",
          "root",
          "-p",
          "example",
          "--quiet",
          "/opt/mongo/joinReplicaSet.js",
        ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 1s
    volumes:
      - ./scripts/mongo/opt/mongo:/opt/mongo
      - ./scripts/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command:
      [
        "--auth",
        "--bind_ip_all",
        "--keyFile",
        "/tmp/mongodb.key",
        "--replSet",
        "dbrs",
      ]
  archivist:
    container_name: archivist
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      ACCOUNT_SEED: "default insecure account seed"
      API_KEY: 00000000-0000-0000-0000-000000000000
      APP_PORT: 8080
      CORS_ALLOWED_ORIGINS: http://localhost:3000
      JWT_SECRET: TOP_SECRET
      MNEMONIC: "sand patient donkey rude degree lady wheel cabin opera relax foil chaos lion shrimp repeat"
      MONGO_CONNECTION_STRING: mongodb://root:example@mongo:27017/?retryWrites=true&w=majority
      MONGO_DATABASE: archivist
      MONGO_DOMAIN: "mongo"
      MONGO_PASSWORD: example
      MONGO_USERNAME: root

**Here is the error I am getting** < Does create endless loop cycle as container will stop then start back up

{"date":"Fri Apr 07 2023 20:05:45 GMT+0000 (Coordinated Universal Time)","error":{"reason":{"commonWireVersion":0,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":"dbrs","stale":false,"type":"ReplicaSetNoPrimary"}},"exception":true,"level":"error","message":"unhandledRejection: connect ECONNREFUSED 127.0.0.1:27017\nMongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Timeout._onTimeout (/app/node_modules/mongodb/src/sdam/topology.ts:564:30)\n    at listOnTimeout (node:internal/timers:569:17)\n    at processTimers (node:internal/timers:512:7)","os":{"loadavg":[0.43,0.4,0.54],"uptime":164306.71},"process":{"argv":["/usr/local/bin/node","/app/dist/cjs/index.js"],"cwd":"/app","execPath":"/usr/local/bin/node","gid":0,"memoryUsage":{"arrayBuffers":36160347,"external":38495394,"heapTotal":90759168,"heapUsed":86016080,"rss":144490496},"pid":28,"uid":0,"version":"v18.15.0"},"stack":"MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at Timeout._onTimeout (/app/node_modules/mongodb/src/sdam/topology.ts:564:30)\n    at listOnTimeout (node:internal/timers:569:17)\n    at processTimers (node:internal/timers:512:7)","timestamp":"2023-04-07T20:05:45.414Z","trace":[{"column":30,"file":"/app/node_modules/mongodb/src/sdam/topology.ts","function":"Timeout._onTimeout","line":564,"method":"_onTimeout","native":false},{"column":17,"file":"node:internal/timers","function":"listOnTimeout","line":569,"method":null,"native":false},{"column":7,"file":"node:internal/timers","function":"processTimers","line":512,"method":null,"native":false}]}
2023-04-07 16:05:45 Done in 32.23s.
2023-04-07 16:05:46 yarn run v1.22.19
2023-04-07 16:05:46 $ node --max-old-space-size=8192 --experimental-specifier-resolution=node ./dist/cjs/index.js
2023-04-07 16:05:46 (node:28) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
2023-04-07 16:05:46 (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by jebscc** [comment]
Think I am getting somewhere now but have to avoid using the archivist container that was built during using the command, "docker compose up". I know this is alpha but wanted to know if the archivist container should be working at this stage or if is this expected until we get a better stable environment.

Either way, this is exciting and finally making a ton of progress!!!

![image](https://user-images.githubusercontent.com/19239389/230674805-247c45e0-49f1-431f-9248-7f6adbab4116.png)

![image](https://user-images.githubusercontent.com/19239389/230674846-ab25d4b8-89b9-4980-85b2-e16156552829.png)

**Comment by JoelBCarter** [comment]
You've got an XYO Node running on your machine!  For my local development, I've just been using the Mongo container from that docker-compose.yml and running the CLI like you.  I'm working on a fully in-memory OR fully MongoDB Node.  I'll try and polish that experience next week and make it so you don't have to use 2 separate repos to get a working local Node.

While you're in there, you should be able to interact with that Node on your machine via the Node/Explore websites by selecting `Local` from the dropdown on the sites.

**Comment by jebscc** [comment]
Joel, I can confirm XYO Explore is able to discover my connected local nodes. Now it's time to see if I can get it to populate any blocks/payloads. 😁

![20230409_215325](https://user-images.githubusercontent.com/19239389/230810038-11b3dd35-9818-4bc2-b9ba-1e027ad6a146.jpg)

**Comment by JoelBCarter** [comment]
This is awesome!  I replied to [your thread over on the SDK repo](https://github.com/XYOracleNetwork/sdk-xyo-client-js/issues/787) as well but I've since removed the `docker-compose.yml` from this repo and migrated it to the SDK repo as it's a better fit there now.  Same process over there

```
docker compose up -d mongo
```

should get you the backing DB you need.  I'm also working a fully in-memory Node so that we can reduce dependency on MongoDB for things like local dev/testing.
